### Prática Função loadtxt()

A função numpy.loadtxt() carrega dados de um ficheiro de texto e fornece uma abordagem rápida para ficheiros de texto simples.

In [1]:
import numpy as np
from io import StringIO

In [2]:
f = StringIO("3 6 8 \n12 9 1 \n2 3 4")

In [3]:
a = np.loadtxt(f)

In [4]:
# A função loadtxt por defeito apresenta o conteudo como sendo float 
print(a)

[[ 3.  6.  8.]
 [12.  9.  1.]
 [ 2.  3.  4.]]


In [5]:
# Converte float para inteiros
b = np.array(a, dtype = "int64")

In [6]:
print(b)

[[ 3  6  8]
 [12  9  1]
 [ 2  3  4]]


In [7]:
#g = [["Fruta, Laranja", "Legume, Tomate"], ["Hortaliça, Batata", "Verdura, Couve"]]
g = [[1, 2], [3, 4]]

In [8]:
print(g)

[[1, 2], [3, 4]]


In [9]:
j = np.matrix(g) 

In [10]:
print(j)

[[1 2]
 [3 4]]


In [11]:
f = StringIO("3, 6, 8 \n12, 9, 1 \n 2, 3, 4")
a = np.loadtxt(f,dtype="int", delimiter = ",")

print(a)

[[ 3  6  8]
 [12  9  1]
 [ 2  3  4]]


In [12]:
f = StringIO("3 6 8 \n7 9 1 \n2 3 4")
(x,y,z) = np.loadtxt(f, dtype = "int", unpack = True)

In [13]:
print(x)
print(y)
print(z)


[3 7 2]
[6 9 3]
[8 1 4]


In [14]:
# Imprimir a coluna 0 e 1 com o uso do delimiter
f = StringIO("3, 6, 8 \n12, 9, 1 \n 2, 3, 4")
a = np.loadtxt(f,dtype="int", usecols = (0,1), delimiter = ",")

print(a)

[[ 3  6]
 [12  9]
 [ 2  3]]


In [15]:

f = StringIO("3 6 8 \n12 9 1 \n 2 3 4")
a = np.loadtxt(f,dtype="int", skiprows = 0)

print(a)

[[ 3  6  8]
 [12  9  1]
 [ 2  3  4]]


In [16]:
f = StringIO("3 6 8 \n12 9 1 \n 2 3 4")
b = np.loadtxt(f, dtype = "int", usecols = (1,2), skiprows = 1)

print(b)

[[9 1]
 [3 4]]


In [20]:
f = StringIO("3 6 8 \n12 9 1 \n 2 3 4")
c = np.loadtxt(f, dtype = "int", skiprows = 2)

print(c)

[2 3 4]


### Matplotlib 2D

#### Visualização de dados com PyPlot

O PyPlot é um módulo do matplotlib para criação de gráficos. Para utilizá-lo é necessário fazer a importação:

In [21]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [22]:
# Criando um gráfico
plt.plot([1,3,5], [2,5,7])
plt.show()

NameError: name 'plt' is not defined

In [ ]:
# Definindo variáveis
x = [1,3,5]
y = [1,2,5]

# Criando um gráfico
plt.plot(x,y)

# Atribuindo um título ao gráfico
plt.title('Exemplo utilizando Plot')
plt.xlabel('Variável 1')
plt.ylabel('Variável 2')

# Atribuindo uma legenda
plt.plot(x, y, label = 'Uma legenda')
plt.legend()

# Exibindo o gráfico gerado
plt.show()

#### Gráfico de Barras

In [ ]:
# Definindo as variáveis
x = [2, 4, 6, 8, 10]
y = [6, 7, 8, 2, 4]

x2 = [1, 3, 5, 7, 9]
y2 = [7, 8, 2, 4, 2]

plt.bar(x, y, label = 'Barrar1', color = 'r')
plt.bar(x2, y2, label = 'Barrar2', color = 'y')

plt.legend()

plt.show()

#### Pie Chart

In [ ]:
# Definindo as variáveis
fatias = [6, 4, 8]
actividades = ['X', 'Y', 'Z']
colunas = ['r', 'm', 'y']

# Criando um gráfico
plt.pie(fatias, labels = actividades, colors = colunas, startangle=90, shadow = True, explode = (0.1, 0, 0))
plt.show()

#### Scatterplot

In [ ]:
# Definindo variáveis 
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [5, 2, 4, 5, 6, 8, 4, 8]

# Criando um gráfico
plt.scatter(x, y, label = 'Pontos', color = 'c', marker = '*', s = 100)
plt.legend()
plt.show()

### Como criar gráficos 3D em Python?

#### 1. Exemplo Básico Gráfico 3D Wireframe Plot

In [ ]:
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
plt.style.use('seaborn-poster')

In [ ]:
fig = plt.figure(figsize = (10, 10))
ax = plt.axes(projection = '3d')
plt.show()

In [ ]:
%matplotlib notebook

In [ ]:
fig = plt.figure(figsize = (8,8))
ax = plt.axes(projection = '3d')
ax.grid()
t = np.arange(0, 10*np.pi, np.pi/50)
x = np.sin(t)
y = np.cos(t)

ax.plot3D(x, y, t)
ax.set_title('3D Parametric Plot')

# Set axes label
ax.set_xlabel('X', labelpad=20)
ax.set_ylabel('Y', labelpad=20)
ax.set_zlabel('Z', labelpad=20)

plt.show()


In [ ]:
print("\n")

In [ ]:
# We can turn off the interactive plot using %matplotlib inline
%matplotlib inline

In [ ]:
x = np.random.random(50)
y = np.random.random(50)
z = np.random.random(50)

fig = plt.figure(figsize = (7, 7)) # Definir o tamanho da figura
ax = plt.axes(projection='3d') # Definir o tipo de ptojecção
ax.grid() 

ax.scatter(x, y, z, c = 'r', s = 50)
ax.set_title('3D Scatter Plot')

# Set axes label
ax.set_xlabel('X', labelpad=20)
ax.set_ylabel('Y', labelpad=20)
ax.set_zlabel('Z', labelpad=20)

plt.show()

In [ ]:
x = [1, 2, 3, 4]
y = [3, 4, 5]

X, Y = np.meshgrid(x,y)

In [ ]:
print(X)

In [ ]:
print(Y)

In [ ]:
fig = plt.figure(figsize = (12, 10))
ax = plt.axes(projection = '3d')

x = np.arange(-5, 5.1, 0.2)
y = np.arange(-5, 5.1, 0.2)

X,Y = np.meshgrid(x,y)
Z = np.sin(X)*np.cos(Y)

surf = ax.plot_surface(X, Y, Z, cmap = plt.cm.cividis)

# Set axes label
ax.set_xlabel('x', labelpad=20)
ax.set_ylabel('y', labelpad=20)
ax.set_zlabel('z', labelpad=20)

fig.colorbar(surf, shrink=0.5, aspect=8)

plt.show()

In [ ]:
fig = plt.figure(figsize = (12,6))

ax = fig.add_subplot(1, 2, 1, projection = '3d')
ax.plot_wireframe(X,Y,Z)
ax.set_title('Wireframe Plot')

ax = fig.add_subplot(1, 2, 2, projection = '3d')
ax.plot_surface(X,Y,Z)
ax.set_title('Surface Plot')

plt.tight_layout()

plt.show()